language: c

sudo: false

addons:
  apt:
    packages:
    - libmysqlclient-dev
    - libpq-dev

env:
  global:
    - LUAROCKS=2.2.2
    - DB_DRIVER=mysql DB_USER=travis DB_NAME=sailor_test
    - DB_DRIVER=postgres DB_USER=postgres DB_NAME=sailor_test

  matrix:
      - LUA=lua5.1
      - LUA=lua5.2
      #- LUA=lua5.3
      - LUA=luajit     # latest stable version (2.0.4)
      # - LUA=luajit2.0  # current head of 2.0 branch
      # - LUA=luajit2.1  # current head of 2.1 branch
      - LUA=luajit+openresty


before_install:
  - source .travis/setenv_lua.sh

install:
  - luarocks make rockspecs/sailor-current-1.rockspec

before_script:
  - source .travis/setdatabases.sh

script:
  - cd test/dev-app
  - if [ ${LUA} != "luajit+openresty" ]; then sailor test --verbose; fi
  - if [ ${LUA} = "luajit+openresty" ]; then sailor test --resty; fi

notifications:
  email:
    on_success: change
    on_failure: always
